"""WS-A state × action matrix: force a planned title into each state and try each service action.
python audit/lab/state_action_matrix.py  -> audit/recon/state-action-matrix.md
"""
from __future__ import annotations
import asyncio, sqlite3, sys, tempfile, shutil
from pathlib import Path
sys.path[:0] = [str(Path(__file__).resolve().parents[2] / "src"), str(Path(__file__).resolve().parents[1])]
from lab.kdplab import CaptureProvider, draft_and_accept, make_root, plan_title  # noqa: E402
from kdp_pipeline.core.state_machine import TitleState  # noqa: E402
from kdp_pipeline.chapter import ChapterService, accept_chapter  # noqa: E402
from kdp_pipeline.context import ContextManifest  # noqa: E402
from kdp_pipeline.planning import PlanningService  # noqa: E402
from kdp_pipeline.models.planning import PlanningArtifactKind  # noqa: E402
from kdp_pipeline.build.service import build_manuscript  # noqa: E402
from kdp_pipeline.release.service import create_release_candidate  # noqa: E402
from kdp_pipeline.verification.service import scan_scripture_placeholders  # noqa: E402
from kdp_pipeline.chapters.service import queue_chapters  # noqa: E402

def main():
    with tempfile.TemporaryDirectory() as tmp:
        base = make_root(Path(tmp) / "base")
        p = CaptureProvider()
        book = plan_title(base, p, chapters=3)
        draft_and_accept(book, p, chapter=1)
        from kdp_pipeline.chapters.service import record_chapter_summary
        record_chapter_summary(base, book.title_id, 1, book.ids["accepted1"], "s", "e")
        d2 = asyncio.run(ChapterService.draft(base, title_id=book.title_id, chapter_number=2, provider=p))
        b0 = build_manuscript(base, title_id=book.title_id, builder="b")
        rows = []
        for state in TitleState:
            root = Path(tmp) / state.value
            shutil.copytree(base, root)
            with sqlite3.connect(root / ".kdp" / "state.db") as c:
                c.execute("update titles set status=?", (state.value,))
                c.execute("update assets set path=replace(path, ?, ?)", (str(base), str(root)))
                c.execute("update manuscript_builds set manifest_path=replace(manifest_path, ?, ?)", (str(base), str(root)))
            def attempt(fn):
                try: fn(); return "allowed"
                except Exception as e: return "blocked"
            prov = CaptureProvider()
            res = {
              "plan: generate outline": attempt(lambda: asyncio.run(PlanningService.generate(root, title_id=book.title_id, artifact_kind=PlanningArtifactKind.OUTLINE, context_manifest=ContextManifest(title_id=book.title_id, task_type="o", inputs=[]), provider=prov))),
              "draft chapter 3": attempt(lambda: asyncio.run(ChapterService.draft(root, title_id=book.title_id, chapter_number=3, provider=CaptureProvider({"chapter.draft.3": "# Three\n\nx\n"})))),
              "accept chapter 2": attempt(lambda: accept_chapter(root, d2.asset.asset_id, chapter_number=2, reviewer="r")),
              "queue chapters": attempt(lambda: queue_chapters(root, book.title_id, 1, 3)),
              "scan scripture": attempt(lambda: scan_scripture_placeholders(root, book.title_id)),
              "build manuscript": attempt(lambda: build_manuscript(root, title_id=book.title_id, builder="b")),
              "create release candidate": attempt(lambda: create_release_candidate(root, title_id=book.title_id, build_id=b0.build.build_id, creator="c")),
            }
            rows.append((state.value, res))
        cols = list(rows[0][1])
        out = ["# State × action matrix (service layer, forced states)\n",
               "Generated by `audit/lab/state_action_matrix.py`. `allowed` = the service completed. Holds (`RIGHTS_HOLD`, `POLICY_HOLD`) and post-release states should block authoring/acceptance/release; they do not everywhere.\n",
               "| State | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
        for state, res in rows:
            out.append(f"| {state} | " + " | ".join(("**allowed**" if res[c] == "allowed" and state in {"RIGHTS_HOLD","POLICY_HOLD","KDP_DRAFT_READY","HUMAN_SUBMITTED","IN_REVIEW","LIVE","MONITORING","KDP_EXCEPTION"} else res[c]) for c in cols) + " |")
        Path("audit/recon/state-action-matrix.md").write_text("\n".join(out) + "\n")
        print("\n".join(out))
main()
